### ISSUE TITLE
"unexpected keyword argument 'stlye'"  when connecting with an R file

### ISSUE THREAD

**Issue by phelps-sg** [jupyter-vim/jupyter-vim#107]
Steps:
1. Run `jupyer qtconsole --kernel=ir`
2. Open an existing R file with cells (`.r` or `.R` extension)
3. Run `:JupyterConnect` in vim

~~~
Error detected while processing function jupyter#UpdateEchom[1]..provider#python3#Call:                                                    
line   18:                                                                                                                                 
Error invoking 'python_execute' on channel 3 (python3-script-host):                                                                        
Traceback (most recent call last):                                                                                                         
  File "<string>", line 1, in <module>                                                                                                     
  File "/home/sphelps/.local/share/lunarvim/site/pack/lazy/opt/jupyter-vim/python3/jupyter_messenger.py", line 334, in timer_echom         
    echom(arg, **args)                                                                                                                     
TypeError: echom() got an unexpected keyword argument 'stlye'  
~~~

**Comment by wmvanvliet** [comment]
I fixed the typo in master. Try it now.

**Comment by phelps-sg** [comment]
Many thanks!  I now get:

~~~
Warning: I don't know how to get infos for a Jupyter kernel of type "ir"
~~~

and when I run the notebook it tries to run it as Python code instead of R.

The console was run using:

~~~
jupyter qtconsole --kernel=ir
~~~

**Comment by wmvanvliet** [comment]
Yeah, I was afraid that would happen. Can you check if PR #108 fixes this for you?

**Comment by phelps-sg** [comment]
Thanks.  Do you happen to know how I can install a specific git branch using Vim Plug?

**Comment by wmvanvliet** [comment]
It's probably possible, but I don't know from the top of my head. I would clone the repo manually in `~/.vim/bundle`
