### ISSUE TITLE
Support for pyenv-virtualenv virtual environment.

### ISSUE THREAD

**Issue by roachsinai** [jupyter-vim/jupyter-vim#21]
## virtual envs

```
hmank ~/./v/3/e/n/bin » la | grep activate
-rw-r--r-- 1 roach roach 2.2K 12月 13 18:46 activate
-rw-r--r-- 1 roach roach 1.3K 12月 13 18:46 activate.csh
-rw-r--r-- 1 roach roach 2.4K 12月 13 18:46 activate.fish
hmank ~/./v/3/e/n/bin » pwd           
/home/roach/.pyenv/versions/3.7.4/envs/nn/bin
```

The env `nn` was created by `pyenv virtualenv 3.7.4 nn`.

## vimrc setting

Setting in vimrc was:

```
let g:vim_virtualenv_path = '/home/roach/.pyenv/versions/3.7.4/envs/nn'
if exists('g:vim_virtualenv_path')
    pythonx import os; import vim
    pythonx activate_this = os.path.join(vim.eval('g:vim_virtualenv_path'), 'bin/activate_this.py')
    pythonx with open(activate_this) as f: exec(f.read(), {'__file__': activate_this})
endif
```

## Error

When use Vim open a file got error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
FileNotFoundError: [Errno 2] 没有那个文件或目录: '/home/roach/.pyenv/versions/3.7.4/envs/nn/bin/activate_this.py'
```

## Reason maybe

There is no active_this.py when using pyenv+virtualenv, only bash script activate.

## Expect

Ways to setting jupyter-vim works with virtual envs created by `pyenv+virtualenv`.

**Comment by tinmarino** [comment]
Can you paste the output of `ls /home/roach/.pyenv/versions/3.7.4/envs/nn/bin/activate_this.py`

**Comment by roachsinai** [comment]
```
hmank ~ » ls /home/roach/.pyenv/versions/3.7.4/envs/nn/bin/activate_this.py
ls: 无法访问 '/home/roach/.pyenv/versions/3.7.4/envs/nn/bin/activate_this.py': 没有那个文件或目录
hmank ~ » ls /home/roach/.pyenv/versions/3.7.4/envs/nn/bin                 
activate                f2py3.7               jupyter                   jupyter-run              pylint          saved_model_cli
activate.csh            google-oauthlib-tool  jupyter-bundlerextension  jupyter-serverextension  pyreverse       skivi
activate.fish           imageio_download_bin  jupyter-kernel            jupyter-troubleshoot     pyrsa-decrypt   symilar
chardetect              imageio_remove_bin    jupyter-kernelspec        jupyter-trust            pyrsa-encrypt   tensorboard
convert-caffe2-to-onnx  iptest                jupyter-lab               markdown_py              pyrsa-keygen    tflite_convert
convert-onnx-to-caffe2  iptest3               jupyter-labextension      pip                      pyrsa-priv2pub  tf_upgrade_v2
easy_install            ipython               jupyter-labhub            pip3                     pyrsa-sign      toco
easy_install-3.7        ipython3              jupyter-migrate           pip3.7                   pyrsa-verify    toco_from_protos
epylint                 isort                 jupyter-nbconvert         pydoc                    python          wheel
f2py                    jlpm                  jupyter-nbextension       pygmentize               python3
f2py3                   jsonschema            jupyter-notebook          pyjson5                  python3.7
hmank ~ » 
```

Yeah, the Chinese means no file.

**Comment by roachsinai** [comment]
```
activate
activate.csh
activate.fish
```
are bash, zsh, fish scripts.

**Comment by tinmarino** [comment]
> Yeah, the Chinese means no file.

Lol !

Then you have no `activate_this.py`. I guess the doc is obsolete. Well I would remove all that and run:
Working : `source /home/roach/.pyenv/versions/3.7.4/envs/nn/bin&& vim`. [stackoverflow](https://stackoverflow.com/questions/3881534/set-python-virtualenv-in-vim)


Nice issue, do not forget to paste the solution you find. Even you can change the README.md and make a Pull Request (PR).

Not working: In vim a `system("/home/roach/.pyenv/versions/3.7.4/envs/nn/bin")` may work but not sure because it may fork a subshell and forget its new envrironment

Working (in vim) : https://github.com/jmcantrell/vim-virtualenv/pull/46/files

**Comment by tinmarino** [comment]
The first solution, to start virtual env before vim, is recommended if you don't want to install `vim-venv`.

I'll have a deeper look on monday for people wishing to put it into their vimrc. It seems that all that must be copyed currently [vim-vitualenv/autoload.pyenv.py](https://github.com/jmcantrell/vim-virtualenv/blob/e7bb5b1960603decf2975f052db672850c5a7de4/autoload/pyvenv.py#L5-L34)

**Comment by roachsinai** [comment]
```
(nn) hmank ~/.jupyter » jupyter qtconsole --generate-config
Traceback (most recent call last):
  File "/home/roach/.pyenv/versions/3.7.4/envs/nn/lib/python3.7/site-packages/qtpy/__init__.py", line 204, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/roach/.pyenv/versions/nn/bin/jupyter-qtconsole", line 6, in <module>
    from qtconsole.qtconsoleapp import main
  File "/home/roach/.pyenv/versions/3.7.4/envs/nn/lib/python3.7/site-packages/qtconsole/qtconsoleapp.py", line 60, in <module>
    from qtpy import QtCore, QtGui, QtWidgets
  File "/home/roach/.pyenv/versions/3.7.4/envs/nn/lib/python3.7/site-packages/qtpy/__init__.py", line 210, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found
```

Should I install `pyqt5` and `PySide`?

**Comment by roachsinai** [comment]
![image](https://user-images.githubusercontent.com/9500049/76703960-ab578a00-6710-11ea-8a52-d731d202e2f7.png)

Activate the virtual env not works.

Error:

```
处理 function jupyter#init_python[4]..<SNR>21_init_python 时发生错误:
第   20 行:
E605: 异常没有被捕获: [jupyter-vim] s:init_python: failed to run Python for initialization: Vim(pythonx):vim.error: Vim(let):E15: 无效的表达式: "could not import jupyter_vim:ImportError: ("Could not find kernel. You *must* install the jupyter package into the\nPython that your vim is linked against. If you are seeing this message, this\nusually means either:\n    (1) configuring vim to automatically load a virtualenv that has Jupyter\n        installed and whose Python interpreter is the same version that your\n        vim is compiled against\n    (2) installing Jupyter using the system Python that vim is using, or\n    (3) recompiling Vim against the Python where you already have Jupyter\n        installed.\nThis is only a requirement to allow Vim to speak with a Jupyter kernel using\nJupyter's own machinery. It does *not* mean that the Jupyter instance with\nwhich you communicate via jupyter-vim needs to be running the same version of\nPython.\n", ModuleNotFoundError("No module named 'jupyter'"
处理 /home/roach/.vim/plugged/jupyter-vim/plugin/jupyter.vim 时发生错误:
第   14 行:
E171: 缺少 :endif
请按 ENTER 或其它命令继续
```

**Comment by tinmarino** [comment]
only run `bash activate`

**Comment by roachsinai** [comment]
Yeah, code block below, `vim-jupyter` in brackets first line is the name of venv.

```
(vim-jupyter) hmank ~ » vim ttt.py
处理 function jupyter#init_python[4]..<SNR>21_init_python 时发生错误:
第   20 行:
E605: 异常没有被捕获: [jupyter-vim] s:init_python: failed to run Python for initialization: Vim(pythonx):vim.error: Vim(let):E15: 无效的表达式: "could not import jupyter_vim:ImportError: ("Could not find kernel. You *must* install the jupyter package into the\nPython that your vim is linked against. If you are seeing this message, this\nusually means either:\n    (1) configuring vim to automatically load a virtualenv that has Jupyter\n        installed and whose Python interpreter is the same version that your\n        vim is compiled against\n    (2) installing Jupyter using the system Python that vim is using, or\n    (3) recompiling Vim against the Python where you already have Jupyter\n        installed.\nThis is only a requirement to allow Vim to speak with a Jupyter kernel using\nJupyter's own machinery. It does *not* mean that the Jupyter instance with\nwhich you communicate via jupyter-vim needs to be running the same version of\nPython.\n", ModuleNotFoundError("No module named 'jupyter'"
处理 /home/roach/.vim/plugged/jupyter-vim/plugin/jupyter.vim 时发生错误:
第   14 行:
E171: 缺少 :endif
```

---

And check I can open qtconsole windown:

![image](https://user-images.githubusercontent.com/9500049/76716965-1040cd80-676d-11ea-91a2-70fff358839e.png)

**Comment by tinmarino** [comment]
Ok, this is surprising. You are definitely right, some code must be changed. They did so in python-mode.
I'll try to reproduce the bug next week (this week in China [I'm in Chile -> Sunday]). I guess you have a vim compiled with `+python3` as output of `vim --version` or `:pythonx import sys; print(sys.version)`.

**Comment by roachsinai** [comment]
Yes,

![image](https://user-images.githubusercontent.com/9500049/76717930-213f0e00-6770-11ea-8ae8-16650fcc9512.png)

HAVE FUN in China!!

**Comment by roachsinai** [comment]
Any updates for this issue in coming days? 😃

**Comment by fdobad** [comment]
I thought I had the same problem using python venv, but now realized that **_console doesn't work, but qtconsole does_**.  
Just don't put the environment activation on vimrc:  
```
let g:vim_virtualenv_path = '/home/roach/.pyenv/versions/3.7.4/envs/nn'
if exists('g:vim_virtualenv_path')
    pythonx import os; import vim
    pythonx activate_this = os.path.join(vim.eval('g:vim_virtualenv_path'), 'bin/activate_this.py')
    pythonx with open(activate_this) as f: exec(f.read(), {'__file__': activate_this})
endif
```
Instead launch vim from an activated environment (`$ source ~/path/to/py3env/bin/activate`), i.e., `(py3env) fdo@f:~$ vim`.  
Be safe and check that you launched vim on the same environment than the qtconsole, hence
```
:pythonx import sys;print(sys.prefix)
In [1]: import sys;print(sys.prefix)
```
Should return the same activated environment directory.

Loaded the plugin at startup the native way, submodule cloning into `.vim/pack/plugin/start/jupyter-vim` directory.  

----------------

But then I wanted to load it on demand, changing `start` to `opt` installation directory, loading it using `:pa jupyter-vim` getting into new trouble, so I added this to my vimrc:
```
" jupyter-vim
nmap <F7> :pa jupyter-vim<CR>:JupyterConnect<CR>
let maplocalleader = "|"
```
So now I have to press <F7> before and after the first opened .py file to make it work
