### ISSUE TITLE
Cannot connect Vim with jupyter-console (Anaconda, Vim, jupyter-console and Windows10)

### ISSUE THREAD

**Issue by ubaldot** [jupyter-vim/jupyter-vim#80]
My setup:

`Windows 10` with `Vim (32 bit)`
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 21 2021 22:13:38)
MS-Windows 32-bit console version
Included patches: 1-3452
Compiled by appveyor@APPVYR-WIN
Huge version without GUI.  Features included (+) or not (-):
+acl                +ex_extra           +multi_lang         -tag_any_white
+arabic             +extra_search       +mzscheme/dyn       +tcl/dyn
+autocmd            -farsi              -netbeans_intg      +termguicolors
+autochdir          +file_in_path       +num64              +terminal
+autoservername     +find_in_path       +packages           -termresponse
-balloon_eval       +float              +path_extra         +textobjects
+balloon_eval_term  +folding            +perl/dyn           +textprop
-browse             -footer             +persistent_undo    -tgetent
++builtin_terms     +gettext/dyn        +popupwin           +timers
+byte_offset        -hangul_input       -postscript         +title
+channel            +iconv/dyn          +printer            -toolbar
+cindent            +insert_expand      +profile            +user_commands
+clientserver       +ipv6               +python/dyn         +vartabs
+clipboard          +job                +python3/dyn        +vertsplit
+cmdline_compl      +jumplist           +quickfix           +virtualedit
+cmdline_hist       +keymap             +reltime            +visual
+cmdline_info       +lambda             +rightleft          +visualextra
+comments           +langmap            +ruby/dyn           +viminfo
+conceal            +libcall            +scrollbind         +vreplace
+cryptv             +linebreak          +signs              +vtp
+cscope             +lispindent         +smartindent        +wildignore
+cursorbind         +listcmds           -sodium             +wildmenu
+cursorshape        +localmap           +sound              +windows
+dialog_con         +lua/dyn            +spell              +writebackup
+diff               +menu               +startuptime        -xfontset
+digraphs           +mksession          +statusline         -xim
-dnd                +modify_fname       -sun_workshop       -xpm_w32
-ebcdic             +mouse              +syntax             -xterm_save
+emacs_tags         -mouseshape         +tag_binary
+eval               +multi_byte_ime/dyn -tag_old_static
```

My `jupyter-console`:

```
Jupyter console 6.4.0

Python 3.8.8 (default, Apr 13 2021, 15:08:07) [MSC v.1916 32 bit (Intel)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.22.0 -- An enhanced Interactive Python. Type '?' for help.
```

My `Windows environment variables`

![image](https://user-images.githubusercontent.com/10845685/138827812-02dc3639-b947-4f33-bf7a-b29cd1efb8df.png)

My `Conda/Anaconda` versions (32 bit):

```
conda 4.10.3
anaconda                  2021.05                  py38_0
```

My `_vimrc`:

```
set encoding=utf-8
set nu
set tabstop=4 softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
set nobackup
set backspace=indent,eol,start
set nocompatible              " required
set clipboard=unnamed
set laststatus=2
set statusline=%f "tail of the filename
set incsearch " for displaying while searching
set smartcase
set hidden
set noswapfile

" Set terminal with 256 colors
set termguicolors
colorscheme desert
set nofoldenable
set foldmethod=syntax
set foldlevelstart=20

" Set fonts for gvim
if has("gui_win32")
    set guifont=Consolas:h11:cANSI
endif

" Automatically open VimGoodies.txt 
"autocmd VimEnter * edit ~/VimGoodies.txt | tabnew

" Buffer management
nnoremap <leader>b :ls<CR>:b
map <C-Left> :bnext<CR>
map <C-Right> :bprev<CR>

" Open terminal below all splits
" For Cygwin
" cabbrev bterm bo term
" For Windows
cabbrev bterm bo terminal powershell

" ALE completion stuff to be set before the plugin.
let g:ale_completion_enabled = 1
let g:ale_completion_autoimport = 1

" --- VUNDLE PLUGIN STUFF BEGIN --------
filetype off                  " required
" Vundle plugin manager
"set the runtime path to include Vundle and initialize
set rtp+=C:/Users/yt75534/vimfiles/bundle/Vundle.vim
 call vundle#begin('C:/Users/yt75534/vimfiles/bundle')
" let Vundle manage Vundle, required
" add all your plugins here (note older versions of Vundle
" used Bundle instead of Plugin)
Plugin 'gmarik/Vundle.vim'
Plugin 'tmhedberg/SimpylFold.vim'
Plugin 'dense-analysis/ale'
Plugin 'ctrlpvim/ctrlp'
Plugin 'nvie/vim-flake8'
Plugin 'davidhalter/jedi-vim'
Plugin 'jpalardy/vim-slime'
Plugin 'jupyter-vim/jupyter-vim'
call vundle#end()            " required
filetype plugin indent on    " required for Vundle
" ---- VUNDLE PLUGIN STUFF END ----------

" ---- Plugin tweak ------
" SimylFold tweak
" Enable folding with the spacebar
nnoremap <space> za

" vim-slime fix paste issues in ipython
"let g:slime_python_ipython = 1
let g:slime_target = "vimterminal"
let g:slime_cell_delimiter = "# %%"
" nmap <C-c><C-v> :call slime#send_cell()<CR>:SlimeSend0 "\r"<CR>
"nmap <C-c><C-x> :call slime#send(getline(".") . "\r"<CR>)
nmap <C-c><C-v> :SlimeSendCurrentLine<CR>
nmap <C-c><C-x> :SlimeSend0<CR>

" vim-jupyter setup
set pythonthreedll=python38.dll
set pythonthreehome=~/Anaconda3
let g:jupyter_mapkeys = 0
let maplocalleader = ','

" Set jedi-vim
" To use Anaconda python
let g:jedi#environment_path = 'C:\Users\yt75534\Anaconda3\python.exe'
" To avoid that it opens the doc while autocompleting
autocmd FileType python setlocal completeopt-=preview
let g:jedi#show_call_signatures = "2" " To avoid showing call signature while typing. To show it, set this to 1.

" Ctrlp stuff
set wildignore+=*\\_out\\*,*\\Cantata\\*
" ctrlp search from current director
let g:ctrlp_cmd='CtrlP :pwd'
let g:ctrlp_max_files=0


"   ALE linter stuff
let g:ale_linters = {'c': ['clangtidy','clangd'],'python':['flake8']}
let g:ale_fixers = {
\   'c':['astyle','clangtidy','remove_trailing_lines', 'trim_whitespace'], 
\}
let g:ale_c_clangtidy_checks = ['*']
let g:ale_c_clangtidy_extra_options = '--extra-arg=-I --extra-arg=C:\Devtools\Install\Cygwin\3.0.7\usr\include --extra-arg=-I --extra-arg=C:\PE_Builds\sw-ecu\BSW\_out\P_AMTG_MC_TEA2P\bin\all_inc' " change header file path if needed
map <C-a><C-a> :ALEGoToDefinition<CR>
map <C-a><C-z> :ALEFindReferences<CR>

" Matlab syntax stuff. To use the code checker use :make
source $VIMRUNTIME/macros/matchit.vim
filetype indent on
autocmd BufEnter *.m    compiler mlint

syntax on
" When using iPython to avoid that shift space gives 32;2u
tnoremap <S-space> <space>

" To have nice colors during autocompletion
hi Pmenu guibg=lightgray guifg=black
hi PmenuSel guibg=darkgray guifg=gray

" In case you use a terminal you want the same
hi Pmenu ctermbg=lightgray ctermfg=black
hi PmenuSel ctermbg=darkgray ctermfg=gray


```

**The error:**
```

Exception ignored in: <function Socket.__del__ at 0x06479028>
Traceback (most recent call last):
  File "C:\Users\yt75534\Anaconda3\lib\site-packages\zmq\sugar\socket.py", line 67, in __del__
    self.close()
  File "C:\Users\yt75534\Anaconda3\lib\site-packages\zmq\_future.py", line 160, in close
    self._clear_io_state()
  File "C:\Users\yt75534\Anaconda3\lib\site-packages\zmq\asyncio\__init__.py", line 60, in _clear_io_state
    self.io_loop.remove_reader(self._fd)
  File "C:\Users\yt75534\Anaconda3\lib\asyncio\events.py", line 504, in remove_reader
    raise NotImplementedError
NotImplementedError: 

```
**Further attempts:**
All the steps from [this](https://github.com/jupyter-vim/jupyter-vim/wiki/Troubleshooting-Windows) guide seem correct with the exception of the Connect part .
Further Googling led me [here](https://jupyter-notebook.readthedocs.io/en/stable/troubleshooting.html).
I tried to do the following (as the troubleshooting guide suggests):
```
conda install --force-reinstall pywin32
python.exe Scripts/pywin32_postinstall.py -install
```
but the problem persists.

**Additional notes:**
- I opened both `vim` and `jupyter-console` from the `Anaconda Powershell prompt`. 
- Execution of `dir ~/AppData/Roaming/jupyter/runtime` shows an incredible long list of `.json` files

```

...
-a----        10/25/2021   9:45 AM            274 kernel-11840.json
-a----         9/30/2021  10:34 AM            274 kernel-12832.json
-a----        10/25/2021   9:50 PM            274 kernel-12892.json
-a----        10/25/2021   2:29 PM            274 kernel-13088.json
-a----         9/30/2021   2:14 PM            274 kernel-13528.json
-a----        10/25/2021   3:13 PM            274 kernel-14280.json
-a----        10/25/2021   2:28 PM            274 kernel-15424.json
-a----        10/25/2021   3:13 PM            274 kernel-17576.json
-a----        10/25/2021   1:32 PM            274 kernel-18312.json
-a----        10/25/2021   1:51 PM            274 kernel-18600.json
-a----        10/25/2021   3:12 PM            274 kernel-1904.json
-a----        10/25/2021   2:47 PM            274 kernel-19108.json
-a----        10/25/2021   1:29 PM            274 kernel-19444.json
-a----        10/25/2021   9:48 PM            274 kernel-19564.json
-a----        10/25/2021   2:26 PM            274 kernel-22004.json
-a----        10/25/2021  10:02 AM            274 kernel-22328.json
-a----        10/25/2021   2:25 PM            274 kernel-22824.json
-a----        10/25/2021   9:54 AM            274 kernel-23512.json
-a----        10/25/2021   3:14 PM            274 kernel-24172.json
-a----        10/25/2021   2:47 PM            274 kernel-24384.json
-a----         9/30/2021   2:02 PM            274 kernel-478ae219fa20.json
-a----        10/25/2021   2:33 PM            274 kernel-4832.json
-a----        10/20/2021  11:32 AM            274 kernel-4a5e619dfcf2.json
-a----        10/19/2021   1:50 PM            274 kernel-4efb867cbe6a.json
-a----         9/30/2021   8:37 AM            274 kernel-70d5415d-ac9c-4434-b57a-fd950bc07e4a.json
-a----        10/25/2021   2:41 PM            274 kernel-9516.json
-a----        10/25/2021  10:07 AM            274 kernel-dcee432f89c8.json
```

**Comment by Appalled** [comment]
I had the same NotImplementedError on windows and got a solution on [stackoverflow](https://stackoverflow.com/questions/58422817/jupyter-notebook-with-python-3-8-notimplementederror). Hope it would be helpful.

Change the end part of the file C:\Users\{USER-NAME}\AppData\Local\Programs\Python\Python38\Lib\asyncio\__init__.py

From

```
if sys.platform == 'win32':  # pragma: no cover
    from .windows_events import *
    __all__ += windows_events.__all__
else:
    from .unix_events import *  # pragma: no cover
    __all__ += unix_events.__all__
```
To

```
import asyncio

if sys.platform == 'win32':
    from .windows_events import *
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
    __all__ += windows_events.__all__
else:
    from .unix_events import *  # pragma: no cover
    __all__ += unix_events.__all__
```

**Comment by Ubaldo79** [comment]
But what if I have installed Python through Anaconda?

**Comment by wmvanvliet** [comment]
I think the key thing here is that on windows, we need to call `asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())` somewhere in the code. We could call this when we initialize the `jupyter-vim` plugin.
